package DiemDanhSV_class;

// default package
// Generated Jul 15, 2018 7:18:40 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * Buoihoc generated by hbm2java
 */
public class Buoihoc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BuoihocId id;
	private Date gioRaVe;
	private String phongHoc;

	public Buoihoc() {
	}

	public Buoihoc(BuoihocId id) {
		this.id = id;
	}

	public Buoihoc(BuoihocId id, Date gioRaVe, String phongHoc) {
		this.id = id;
		this.gioRaVe = gioRaVe;
		this.phongHoc = phongHoc;
	}

	public BuoihocId getId() {
		return this.id;
	}

	public void setId(BuoihocId id) {
		this.id = id;
	}

	public Date getGioRaVe() {
		return this.gioRaVe;
	}

	public void setGioRaVe(Date gioRaVe) {
		this.gioRaVe = gioRaVe;
	}

	public String getPhongHoc() {
		return phongHoc;
	}

	public void setPhongHoc(String phongHoc) {
		this.phongHoc = phongHoc;
	}

}
