package DiemDanhSV_class;
// Generated Jul 11, 2018 11:12:50 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Buoihoc generated by hbm2java
 */
@Entity
@Table(name = "buoihoc", catalog = "diemdanhsinhvien")
public class Buoihoc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 42834232717204514L;
	private BuoihocId id;

	public Buoihoc() {
	}

	public Buoihoc(BuoihocId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "maTkb", column = @Column(name = "ma_tkb", nullable = false)),
			@AttributeOverride(name = "ngayHoc", column = @Column(name = "ngay_hoc", nullable = false, length = 10)),
			@AttributeOverride(name = "gioHoc", column = @Column(name = "gio_hoc", nullable = false, length = 8)) })
	public BuoihocId getId() {
		return this.id;
	}

	public void setId(BuoihocId id) {
		this.id = id;
	}

}
