package DiemDanhSV_class;

// default package
// Generated Jul 15, 2018 7:18:40 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Diemdanh generated by hbm2java
 */
public class Diemdanh implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private DiemdanhId id;
	private Boolean daDiHoc;

	public Diemdanh() {
	}

	public Diemdanh(DiemdanhId id) {
		this.id = id;
	}

	public Diemdanh(DiemdanhId id, Boolean daDiHoc) {
		this.id = id;
		this.daDiHoc = daDiHoc;
	}

	public DiemdanhId getId() {
		return this.id;
	}

	public void setId(DiemdanhId id) {
		this.id = id;
	}

	public Boolean getDaDiHoc() {
		return this.daDiHoc;
	}

	public void setDaDiHoc(Boolean daDiHoc) {
		this.daDiHoc = daDiHoc;
	}

}
