package DiemDanhSV_class;

// default package
// Generated Jul 15, 2018 7:18:40 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Monhoc generated by hbm2java
 */
public class Monhoc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String maMonHoc;
	private String tenMonHoc;

	public Monhoc() {
	}

	public Monhoc(String maMonHoc, String tenMonHoc) {
		this.maMonHoc = maMonHoc;
		this.tenMonHoc = tenMonHoc;
	}

	public String getMaMonHoc() {
		return this.maMonHoc;
	}

	public void setMaMonHoc(String maMonHoc) {
		this.maMonHoc = maMonHoc;
	}

	public String getTenMonHoc() {
		return this.tenMonHoc;
	}

	public void setTenMonHoc(String tenMonHoc) {
		this.tenMonHoc = tenMonHoc;
	}

}
