package DiemDanhSV_class;

// default package
// Generated Jul 15, 2018 7:18:40 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Nguoidung generated by hbm2java
 */
public class Nguoidung implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String tenDn;
	private String matKhau;
	private String hoTen;
	private int quyen;

	public Nguoidung() {
	}

	public Nguoidung(String tenDn, String matKhau, int quyen) {
		this.tenDn = tenDn;
		this.matKhau = matKhau;
		this.quyen = quyen;
	}
	
	public Nguoidung(String tenDn, String matKhau) {
		this.tenDn = tenDn;
		this.matKhau = matKhau;
		this.quyen = 1;
	}

	public Nguoidung(String tenDn, String matKhau, String hoTen, int quyen) {
		this.tenDn = tenDn;
		this.matKhau = matKhau;
		this.hoTen = hoTen;
		this.quyen = quyen;
	}

	public String getTenDn() {
		return this.tenDn;
	}

	public void setTenDn(String tenDn) {
		this.tenDn = tenDn;
	}

	public String getMatKhau() {
		return this.matKhau;
	}

	public void setMatKhau(String matKhau) {
		this.matKhau = matKhau;
	}

	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	public int getQuyen() {
		return this.quyen;
	}

	public void setQuyen(int quyen) {
		this.quyen = quyen;
	}

}
