package DiemDanhSV_class;
// Generated Jul 11, 2018 11:12:50 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Nguoidung generated by hbm2java
 */
@Entity
@Table(name = "nguoidung", catalog = "diemdanhsinhvien")
public class Nguoidung implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String tenDn;
	private String matKhau;
	private String hoTen;
	private int quyen;

	public Nguoidung() {
	}
	
	public Nguoidung(String tenDn,String matKhau) {
		this.tenDn = tenDn;
		this.matKhau = matKhau;
	}

	public Nguoidung(String tenDn, String matKhau, int quyen) {
		this.tenDn = tenDn;
		this.matKhau = matKhau;
		this.quyen = quyen;
	}

	public Nguoidung(String tenDn, String matKhau, String hoTen, int quyen) {
		this.tenDn = tenDn;
		this.matKhau = matKhau;
		this.hoTen = hoTen;
		this.quyen = quyen;
	}

	@Id

	@Column(name = "ten_dn", unique = true, nullable = false, length = 32)
	public String getTenDn() {
		return this.tenDn;
	}

	public void setTenDn(String tenDn) {
		this.tenDn = tenDn;
	}

	@Column(name = "mat_khau", nullable = false, length = 128)
	public String getMatKhau() {
		return this.matKhau;
	}

	public void setMatKhau(String matKhau) {
		this.matKhau = matKhau;
	}

	@Column(name = "ho_ten", length = 128)
	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	@Column(name = "quyen", nullable = false)
	public int getQuyen() {
		return this.quyen;
	}

	public void setQuyen(int quyen) {
		this.quyen = quyen;
	}

}
